#! /bin/bash

tempfile="/tmp/contur-"$RANDOM
#awk '{print $1,$2,$4*0.0000001}' $1 >$tempfile
#awk '{print $1,$2,$3}' $1 >$tempfile
awk '{print $1,$2,$5}' $1 >$tempfile
datafile='"'$tempfile'"'
plot="plot $datafile with image"
gnuplot << EOF
set terminal postscript eps color enhanced solid "Helvetica" 12
set output "gplot.eps"
reset
unset key
#set yrange [-90:90]
#set xrange [1.1:3]
set yrange [-5:5]
set xrange [1.8:2.1]

#set palette rgbformulae 33,13,10
set palette gray negative
set xlabel "nomalized radial distance[R_{s}]"
set ylabel "latitude[degree]"
set format cb "%.1t*e%+02T"
set cntrparam levels  10
#set cblabel "[m/s^2]" rotate by 0 offset -5,-20  

$plot
pause  mouse button2
EOF
